### PR TITLE
Frontend Overhaul

### PR DESCRIPTION
**Pull request by lolPants**
Switched from Bootstrap 3 to Bulma

Re-worked all the HTML to work with Bulma and made the site as a whole look more modern.
It also now works (mostly) on mobile devices.

### CODE REVIEW

**Comment by Byorun** [comment]
I merged your branch with the layout-test branch.
* I noticed that you still reference images from the default theme.
* I for me it still looks the same (only /auth/login shows the new theme, the other pages look the same)

https://beatsaver.cyber-cortex.net/auth/login  <-- checked out the branch

**Comment by Byorun** [comment]
@beatsaver I checked out the current version at the above link. For me its ok.

**Comment by lolPants** [comment]
Just realized I forgot to make mobile support work properly... one sec

**Comment by lolPants** [comment]
This new theme also fixes #38

**Pull request merged**
